# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Updates for Gemfile, used to run GitHub Pages locally
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'weekly'
  # Updates for GitHub Actions, used to build and deploy GitHub Pages
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
  # Updates for npm, used to provide libraries for the website
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"