language: node_js
before_script:
- npm install
script:
- npm run test
after_success:
- git config --global user.email "deploy@travis-ci.org"
- git config --global user.name "Deployment Bot"
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
