language: node_js
before_script:
- npm install
script:
- npm run test
after_success:
- ./prepare_gh_deploy.sh
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
env:
  global:
  - GH_REPO=redbox-mint/docs-redboxresearchdata
  - GIT_NAME=DeploymentBot
  - GIT_EMAIL=deploy@travis-ci.org
  - secure: luTtXlSF8tcyORiL6mmhP81MQmRtJh++TxByfcNCwogy7qjiiggZTmyZ0fMCIWPfUuuhok4aI78qutajYfm1pk5FJfg6Pq9q2V9JJoI+rvMaAXpL1nyiddZN16uYK0mCkzPJPbWU8QGYijygIAv/5Pw9qmK4D95gvZWQwUusdUJotoVXYf9DaBTFXx1KSJB9B45m3knaUF8KTZ+77//LPj3oxt2/uoN6rdbjDFwE38VJXKfP+ThnauDPPJ61ddyMQDr7AlytUf8VZrATd8+oooDwgqVQk1Fnd/fHTtsttuwnzDZnbknoSxa8+dNyu0MoHA7m6t0o2M5QA5YDoiTE6WX4Nh7bBBui91KqxcLsN+b7+cqvtVjihixcOFzto6Bs5QSt7drdcARxZ1lTEW7IUOd+IO9IIY0qhp89FkFbsQLY8qlU/q4Crii6BQLNeVUzq1pcCcJwnjkzp2nMqjGLwzQ70QzcwzHxMG6LhTlIYy3AsAUPDtnQ2RQZEKYbds71BSlp5Hu3uchuhbRyc+FaYIdtt0LOtoU8fNNX5hpJD20aglSuGwHCUZfE5Nj8F1E7xvso0rvTRzHMblMVzcGbSlvZwOtvViK8PxRVvxNGqAck4rYelYUCRAQE9v2ZSk5WzsCIY4do5lSfOor6bYoJhnnN6W/wg8Rw9/pmhAcoXOI=
